version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gochecknoinits
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - hugeParam
        - commentedOutCode
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      confidence: 0.1
      rules:
        - name: package-comments
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocritic
        text: re-assignment to `err` can be replaced with
      - linters:
          - staticcheck
        text: at least one file in a package should have a package comment
      - linters:
          - revive
        text: should have a package comment, unless it's in another file for this package
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: 'shadow: declaration of "err" shadows declaration at'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
