name: Lint
on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - name: Checkout code
        uses: actions/checkout@v5
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
