name: Publish driver-did-iden3
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_driver:
    env:
      STATE_CONTRACT_ADDRESS_MAIN: "0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D"
      STATE_CONTRACT_ADDRESS_AMOY: "0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124"
      STATE_CONTRACT_ADDRESS_PRIVADO: "0x975556428F077dB5877Ea2474D783D6C69233742"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout driver-did-iden3
        uses: actions/checkout@v3
        with:
          path: driver-did-iden3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build file with supported networks
        run: |
          cd driver-did-iden3
          echo -e "polygon:" > resolvers.settings.yaml
          echo -e "  amoy:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_AMOY }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.POLYGON_AMOY_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "  main:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_MAIN }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.POLYGON_MAIN_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "privado:" > resolvers.settings.yaml
          echo -e "  main:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_PRIVADO }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.PRIVADO_MAIN_NODE_URL }}" >> resolvers.settings.yaml
          echo -e "  test:" >> resolvers.settings.yaml
          echo -e "    contractAddress: ${{ env.STATE_CONTRACT_ADDRESS_PRIVADO }}" >> resolvers.settings.yaml
          echo -e "    networkURL: ${{ secrets.PRIVADO_TEST_NODE_URL }}" >> resolvers.settings.yaml

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: build and deploy to DockerHub
        run: |
          cd driver-did-iden3 && \
          docker buildx build --push \
           --platform linux/amd64,linux/arm64 \
           -t ghcr.io/iden3/driver-did-iden3:${{ github.ref_name }} \
           -t ghcr.io/iden3/driver-did-iden3:latest .
